package com.hanhan.n8.semaphore;

import lombok.extern.slf4j.Slf4j;

import java.util.concurrent.Semaphore;

import static java.lang.Thread.sleep;

@Slf4j(topic = "c.semaphoreTests")
public class semaphoreTests {
    public static void main(String[] args) {
//        test();

    }

    private static void test() {
        /*
        23:24:48.419 [Thread-0] DEBUG c.semaphoreTests - running...
        23:24:48.419 [Thread-1] DEBUG c.semaphoreTests - running...
        23:24:48.419 [Thread-2] DEBUG c.semaphoreTests - running...
        23:24:48.426 [Thread-0] DEBUG c.semaphoreTests - end...
        23:24:48.426 [Thread-1] DEBUG c.semaphoreTests - end...
        23:24:48.426 [Thread-2] DEBUG c.semaphoreTests - end...
        23:24:48.426 [Thread-7] DEBUG c.semaphoreTests - running...
        23:24:48.426 [Thread-5] DEBUG c.semaphoreTests - running...
        23:24:48.426 [Thread-6] DEBUG c.semaphoreTests - running...
        23:24:48.428 [Thread-7] DEBUG c.semaphoreTests - end...
        23:24:48.428 [Thread-6] DEBUG c.semaphoreTests - end...
        23:24:48.428 [Thread-5] DEBUG c.semaphoreTests - end...
        23:24:48.428 [Thread-4] DEBUG c.semaphoreTests - running...
        23:24:48.428 [Thread-3] DEBUG c.semaphoreTests - running...
        23:24:48.428 [Thread-9] DEBUG c.semaphoreTests - running...
        23:24:48.430 [Thread-3] DEBUG c.semaphoreTests - end...
        23:24:48.430 [Thread-9] DEBUG c.semaphoreTests - end...
        23:24:48.430 [Thread-4] DEBUG c.semaphoreTests - end...
        23:24:48.430 [Thread-8] DEBUG c.semaphoreTests - running...
        23:24:48.432 [Thread-8] DEBUG c.semaphoreTests - end...
         */
        // 1. 创建 semaphore 对象
        Semaphore semaphore = new Semaphore(3);
        // 2. 10个线程同时运行
        for (int i = 0; i < 10; i++) {
            new Thread(() -> {
                // 3. 获取许可
                try {
                    semaphore.acquire();
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                try {
                    log.debug("running...");
                    try {
                        sleep(1);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                    log.debug("end...");
                } finally {
                    // 4. 释放许可
                    semaphore.release();
                }
            }).start();
        }
    }
}
