server:
  port: 80
spring:
  application:
    name: cloud-order-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
#      defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: https://eureka7001.com:7001/eureka/,https://eureka7002.com:7002/eureka/
