server:
  port: 80

spring:
  application:
    name: cloud-consumer-payment
  cloud:
    consul:
      host: localhost
      prot: 8500
      discovery:
        service-name: ${spring.application.name}
